project_name: ybm
builds:
- env:
  - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
  - -trimpath
  ldflags:
  - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  binary: '{{ .ProjectName }}'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
milestones:
  - close: true
brews:
  - tap:
      owner: yugabyte
      name: ybm-cli
    folder: Formula
    homepage: "https://github.com/yugabyte/ybm-cli"
    # Allows you to set a custom download strategy.
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    # Allows you to add a custom require_relative at the top of the formula template
    custom_require: "lib/custom_download_strategy"
    description: "YugabyteDB Managed CLI"
    license: "Apache"