name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - 
        name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.GO_CLIENT_SECRET }}' > ~/.ssh/id_ed25519
          sudo chmod 0400 ~/.ssh/id_ed25519
          git config --global url."git@github.com:".insteadOf https://github.com/
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.6.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Clean upSSH key
        run: |
          sudo rm -rf ~/.ssh/id_ed25519
