name: YB Manged CLI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  # Permission for checking out code
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/yugabyte/yugabytedb-managed-go-client-internal"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.GO_CLIENT_SECRET }}'
          git config --global url."git@github.com:".insteadOf https://github.com/
          make build
          make clean
        name: Build provider
