name: YB Managed CLI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  # Permission for checking out code
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/yugabyte/yugabytedb-managed-go-client-internal"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.GO_CLIENT_SECRET }}'
          git config --global url."git@github.com:".insteadOf https://github.com/
          make vet
          make build
          make clean
        name: Build CLI
